# Generated by Django 5.0.3 on 2025-09-12 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(null=True, upload_to='teamslogos')),
                ('created_by', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('batter', 'batter'), ('bowler', 'bowler'), ('wicketkeeper', 'wicketkeeper'), ('all-rounder', 'all-rounder')], max_length=50, null=True)),
                ('batting_style', models.CharField(choices=[('right-handed', 'right-handed'), ('left-handed', 'left-handed')], max_length=50, null=True)),
                ('balling_style', models.CharField(choices=[('right-arm-fast', 'right-arm-fast'), ('right-arm-spin', 'right-arm-spin'), ('lef-arm-fast', 'left-arm-fast'), ('left-arm-spin', 'left-arm-spin')], max_length=50, null=True)),
                ('matches', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('created_by', models.CharField(max_length=256)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='Records.team')),
            ],
        ),
    ]
