# Generated by Django 5.0.3 on 2025-09-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='First_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Last_name',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='runs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wickets',
        ),
        migrations.CreateModel(
            name='BallingPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('overs', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('threeWicketsHall', models.IntegerField(default=0)),
                ('fiveWicketsHall', models.IntegerField(default=0)),
                ('hattricks', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('maidens', models.IntegerField(default=0)),
                ('noBalls', models.IntegerField(default=0)),
                ('wides', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.player')),
            ],
        ),
        migrations.CreateModel(
            name='BattingPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('singles', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('tripples', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('not_outs', models.IntegerField(default=0)),
                ('high_score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.player')),
            ],
        ),
        migrations.CreateModel(
            name='FieldingPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('dropped', models.IntegerField(default=0)),
                ('runouts', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.player')),
            ],
        ),
        migrations.CreateModel(
            name='wicketKeeperPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('stumppings', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.player')),
            ],
        ),
    ]
