# Generated by Django 5.0.3 on 2025-09-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0002_rename_first_name_player_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='balling_style',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='batting_style',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
