# Generated by Django 5.0.3 on 2025-09-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0003_alter_player_balling_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(null=True, upload_to='teamlogos/'),
        ),
    ]
