# Generated by Django 5.0.3 on 2025-09-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0004_alter_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
    ]
