# Generated by Django 5.0.3 on 2025-09-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0006_alter_team_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.profile'),
        ),
    ]
