# Generated by Django 5.0.3 on 2025-09-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0007_alter_player_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
