# Generated by Django 5.0.3 on 2025-09-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0008_player_created_at_team_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballingperformance',
            name='overs',
        ),
        migrations.RemoveField(
            model_name='ballingperformance',
            name='played',
        ),
        migrations.RemoveField(
            model_name='battingperformance',
            name='high_score',
        ),
        migrations.RemoveField(
            model_name='battingperformance',
            name='not_outs',
        ),
        migrations.RemoveField(
            model_name='battingperformance',
            name='played',
        ),
        migrations.RemoveField(
            model_name='fieldingperformance',
            name='played',
        ),
        migrations.RemoveField(
            model_name='wicketkeeperperformance',
            name='played',
        ),
    ]
