# Generated by Django 5.0.3 on 2025-09-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0009_remove_ballingperformance_overs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingperformance',
            name='is_out',
            field=models.BooleanField(default=True),
        ),
    ]
