# Generated by Django 5.0.3 on 2025-09-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0010_battingperformance_is_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.FileField(null=True, upload_to='teamlogos/'),
        ),
    ]
