# Generated by Django 5.0.3 on 2025-09-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0013_alter_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballingperformance',
            name='fiveWicketsHall',
        ),
        migrations.RemoveField(
            model_name='ballingperformance',
            name='noBalls',
        ),
        migrations.RemoveField(
            model_name='ballingperformance',
            name='threeWicketsHall',
        ),
        migrations.AddField(
            model_name='ballingperformance',
            name='no_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ballingperformance',
            name='hattricks',
            field=models.BooleanField(default=False),
        ),
    ]
