# Generated by Django 5.0.3 on 2025-09-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0014_remove_ballingperformance_fivewicketshall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingperformance',
            name='dot',
            field=models.IntegerField(default=0),
        ),
    ]
